// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFtOv_JTfXN3T4QqXqijXg-9kI8-xAaEY',
    appId: '1:251865980047:web:19c66fd15e819a933ae4fa',
    messagingSenderId: '251865980047',
    projectId: 'awarness-x',
    authDomain: 'awarness-x.firebaseapp.com',
    storageBucket: 'awarness-x.appspot.com',
    measurementId: 'G-VH4VXXVRJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAroqDsPZENxfvtYheEP8lVijlJg5mW2fE',
    appId: '1:251865980047:android:938634d2a967f0d53ae4fa',
    messagingSenderId: '251865980047',
    projectId: 'awarness-x',
    storageBucket: 'awarness-x.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFPKi_SK8fh9MiMmrMsVOoG8ouAorCpcM',
    appId: '1:251865980047:ios:3a50ca519ff723f93ae4fa',
    messagingSenderId: '251865980047',
    projectId: 'awarness-x',
    storageBucket: 'awarness-x.appspot.com',
    iosBundleId: 'com.example.scan2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFPKi_SK8fh9MiMmrMsVOoG8ouAorCpcM',
    appId: '1:251865980047:ios:fb049b03c718afcb3ae4fa',
    messagingSenderId: '251865980047',
    projectId: 'awarness-x',
    storageBucket: 'awarness-x.appspot.com',
    iosBundleId: 'com.example.scan2.RunnerTests',
  );
}
